version: "3"

services:
  practice-notify:
    container_name: practice-notify
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    tty: true
    volumes:
      - ./:/app
