FROM python:3.9-slim-buster
# Allow statements and log messages to immediately appear in the Knative logs
ENV PYTHONUNBUFFERED True

ENV APP_HOME /app
WORKDIR $APP_HOME

# Install production dependencies.
RUN pip3 install --upgrade google-api-python-client
